import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavLink from "@/components/NavLink";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <div className="flex justify-between mb-4 ">
          <Image src="./next.svg"
                 alt="receipe logo"
                 width={100}
                 height={100}
                 className="m-4"
          />

          <nav className="flex justify-center m-4">
              <NavLink url="/" pageName="Home"/>
              <NavLink url="/add-recipe" pageName="Add recipe"/>
          </nav>
      </div>
      <div className="container mx-auto">
          {children}
      </div>

      </body>
    </html>
  );
}
